# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Willard en Español
email: wdn5796@rit.edu
description: > # this means to ignore newlines until "baseurl:"
  Un blog de Will Nilges—en Español!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willard-en-espanol.gq" # the base hostname & protocol for your site
twitter_username: null
github_username:  willnilges

# Build settings
markdown: kramdown
